name: tcc
description: A new Flutter project.



publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"



dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter 

  cupertino_icons: ^1.0.2
  flutter_modular: ^4.5.1+1
  flutter_triple: ^1.2.7+2
  
  syncfusion_flutter_charts: ^20.1.52
  firebase_core: ^1.16.0
  cloud_firestore: ^3.1.14
  firebase_auth: ^3.3.17
  dartz: ^0.10.1
  flutter_secure_storage: ^5.0.2
  google_fonts: ^2.3.2
  intl: ^0.17.0
  flutter_form_builder: ^7.1.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0
  triple_test: ^1.0.0
  modular_test: ^1.0.1+2


flutter:


  uses-material-design: true

  assets:
  - assets/images/
