// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBzvN64m02t_vyccm93iPdhxfNDGTnWuo',
    appId: '1:370019520366:web:f8db872ac7839447ccfb7f',
    messagingSenderId: '370019520366',
    projectId: 'tcc-wennys',
    authDomain: 'tcc-wennys.firebaseapp.com',
    storageBucket: 'tcc-wennys.appspot.com',
    measurementId: 'G-FYP11J6PKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbuqJJpVK_a_OwIqRQMXZUD8gpJ6FzgIE',
    appId: '1:370019520366:android:1ef2a05db1e24f6fccfb7f',
    messagingSenderId: '370019520366',
    projectId: 'tcc-wennys',
    storageBucket: 'tcc-wennys.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHKdBdNSCmZXo25HK6pPgFGUiFCDbGLRo',
    appId: '1:370019520366:ios:87963c8f0e9d7967ccfb7f',
    messagingSenderId: '370019520366',
    projectId: 'tcc-wennys',
    storageBucket: 'tcc-wennys.appspot.com',
    iosClientId: '370019520366-86slpgni0ajp83t61b964mqsh32rtkpn.apps.googleusercontent.com',
    iosBundleId: 'com.wennystcc.app',
  );
}
